### ISSUE TITLE
필승! 배너 사진 등록 문제입니다

### ISSUE THREAD

**Issue by GyeongHoKim** [alsrb9936/alsrb9936.github.io#1]
방금 **아 안된다고** 라는 commit을 확인해 본 결과, index.html 파일에 다음과 같은 코드를 추가한 것을 확인.

```
---
layout: home
author_profile: true
header:
	image: [/assets/images/banner.png]

---
```

여기서 []에 감탄. 생활관 쓰레기통을 뒤지던 짬타이거가 이 코드를 높이 평가. 본 짬타이거 이 코드에 감복하여 정문 초소 헌병을 때려눕히고 탈영을 시도. 그러나 이 코드를 다음과 같이 변환 요망.

```
---
layout: home
author_profile: true
header:
	image: /assets/images/banner.png

---
```

이 리포트를 역사가 높이 평가
필승!

**Comment by alsrb9936** [comment]
코드 수듄 린정
팩폭 강도 조절 요망....
